name: build and containerize

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  AWS_REGION: ap-southeast-2
  ECR_REPO_NAME: cjaydevops/user-management
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  DOCKER_IMAGE: user-management
  CD_REPO: git@github.com:Cjay13/user-management-cd.git
  CD_BRANCH: main
  VALUES_FILE: user-management-helm/values.yaml
  

jobs:
  build:
    name: Build and Sonar Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=cjay-practice-projects
            -Dsonar.projectKey=cjay-practice-projects_ecom-usermanagement
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=src/main/java
            -Dsonar.java.binaries=target/classes
            -Dsonar.tests=src/test/java
            -Dsonar.test.exclusions=tests/**
            -Dsonar.verbose=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Get Commit SHA
        id: commit
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Docker Build
        run: |
          docker build -t $DOCKER_IMAGE:$COMMIT_SHA .
          docker tag $DOCKER_IMAGE:$COMMIT_SHA $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$COMMIT_SHA

      - name: debug
        run: docker images

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_NAME }}:${{ env.COMMIT_SHA }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push Docker image to Amazon ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$COMMIT_SHA

      - name: Setup SSH Key
        run:  
          mkdir -p ~/.ssh
          ls -a ~/.ssh
          echo "${{ secrets.SSH_PVT_KEY }}"
          # > ~/.ssh/id_ed25519
          # chmod 600 ~/.ssh/id_ed25519
          # ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Update values.yaml
        run: |
  
          IMAGE_TAG=$COMMIT_SHA
                  
          git clone $CD_REPO cd-repo
          cd cd-repo
          
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          sed -i "s|tag: .*|tag: \"${IMAGE_TAG}\"|" $VALUES_FILE

          git add $VALUES_FILE
          git commit -m "Updated image tag to ${IMAGE_TAG}"
          git push origin $CD_BRANCH
        

          
          
          
        
